### ISSUE TITLE
celery 4.4.0 conflicts with vine 5.0.0

### ISSUE THREAD

**Issue by zhangyi-hu** [conda-forge/airflow-feedstock#58]
```
celery --version 
Traceback (most recent call last):
  File "/opt/conda/bin/celery", line 6, in <module>
    from celery.__main__ import main
  File "/opt/conda/lib/python3.7/site-packages/celery/__init__.py", line 153, in <module>
    from . import local  # noqa
  File "/opt/conda/lib/python3.7/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/opt/conda/lib/python3.7/site-packages/celery/five.py", line 7, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'

```

After install vine 1.3.0, the problem is fixed. I suggest change the version of vine under airflow-with-celery to be fixed at 1.3.0. 

This solution was also suggested in https://stackoverflow.com/questions/32757259/celery-no-module-named-five

**Comment by zhangyi-hu** [comment]
The recipe for conda-forge celery  is also declaring vine 1.3.0 as a dependency:

https://github.com/conda-forge/celery-feedstock/blob/51130d0d12f1f01feefa56534e1e58a8bea53c1b/recipe/meta.yaml#L29

**Comment by xylar** [comment]
@zhangyi-hu, I'm a little confused about this.  I just fixed this yesterday in #55, specifically:
https://github.com/conda-forge/airflow-feedstock/pull/55/commits/a14bfa55dfef5301745f415a45aeda77c88ff9b6

Could you please post your `conda list` info (this was requested when you create an issue) to see if you are using the version I just fixed?

Also, while the latest celery does pin the version of vine, the earlier version required by airflow apparently did not.

**Comment by xylar** [comment]
It works for me under linux:
```
$ conda create -y -n test python=3.8 airflow-with-celery
```
<details>

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/xylar/miniconda3/envs/test

  added / updated specs:
    - airflow-with-celery
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    airflow-1.10.12            |   py38h32f6830_2         4.1 MB  conda-forge
    airflow-with-celery-1.10.12|                2          13 KB  conda-forge
    python-3.8.6               |h852b56e_0_cpython        22.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        26.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  airflow            conda-forge/linux-64::airflow-1.10.12-py38h32f6830_2
  airflow-with-cele~ conda-forge/linux-64::airflow-with-celery-1.10.12-2
  alembic            conda-forge/noarch::alembic-1.4.3-pyh9f0ad1d_0
  amqp               conda-forge/noarch::amqp-2.6.1-pyh9f0ad1d_0
  anyjson            conda-forge/linux-64::anyjson-0.3.3-py38_1001
  apispec            conda-forge/noarch::apispec-1.3.3-py_0
  argcomplete        conda-forge/noarch::argcomplete-1.10.3-py_0
  argon2-cffi        conda-forge/linux-64::argon2-cffi-20.1.0-py38h1e0a361_1
  arrow              conda-forge/linux-64::arrow-0.17.0-py38h32f6830_0
  atk                conda-forge/linux-64::atk-2.36.0-2
  atk-1.0            conda-forge/linux-64::atk-1.0-2.36.0-h516909a_2
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  babel              conda-forge/noarch::babel-2.8.0-py_0
  bcrypt             conda-forge/linux-64::bcrypt-3.2.0-py38h1e0a361_0
  billiard           conda-forge/linux-64::billiard-3.6.3.0-py38h516909a_0
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py38h1e0a361_1000
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.6.20-hecda079_0
  cached-property    conda-forge/noarch::cached-property-1.5.1-py_0
  cairo              conda-forge/linux-64::cairo-1.16.0-h3fc0475_1005
  cattrs             conda-forge/noarch::cattrs-1.0.0-py_0
  celery             conda-forge/noarch::celery-4.4.0rc1-py_0
  certifi            conda-forge/linux-64::certifi-2020.6.20-py38h32f6830_0
  cffi               conda-forge/linux-64::cffi-1.14.3-py38h5bae8af_0
  chardet            conda-forge/linux-64::chardet-3.0.4-py38h32f6830_1007
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  colorama           conda-forge/noarch::colorama-0.4.3-py_0
  colorlog           conda-forge/linux-64::colorlog-4.0.2-py38_1000
  colour             conda-forge/noarch::colour-0.1.5-py_0
  configparser       conda-forge/noarch::configparser-3.5.0-py_1000
  croniter           conda-forge/noarch::croniter-0.3.34-pyh9f0ad1d_0
  cryptography       conda-forge/linux-64::cryptography-3.1.1-py38h766eaa4_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  dill               conda-forge/noarch::dill-0.3.2-pyh9f0ad1d_0
  dnspython          conda-forge/noarch::dnspython-2.0.0-py_0
  docutils           conda-forge/linux-64::docutils-0.16-py38h32f6830_1
  email-validator    conda-forge/noarch::email-validator-1.1.1-pyh9f0ad1d_0
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  flask              conda-forge/noarch::flask-1.1.2-pyh9f0ad1d_0
  flask-admin        conda-forge/noarch::flask-admin-1.5.4-py_0
  flask-appbuilder   conda-forge/noarch::flask-appbuilder-2.2.4-py_0
  flask-babel        conda-forge/noarch::flask-babel-1.0.0-py_0
  flask-caching      conda-forge/noarch::flask-caching-1.3.3-py_0
  flask-jwt-extended conda-forge/noarch::flask-jwt-extended-3.24.1-pyh9f0ad1d_0
  flask-login        conda-forge/noarch::flask-login-0.4.1-py_0
  flask-openid       conda-forge/linux-64::flask-openid-1.2.5-py38_1003
  flask-sqlalchemy   conda-forge/noarch::flask-sqlalchemy-2.4.4-pyh9f0ad1d_0
  flask-swagger      conda-forge/noarch::flask-swagger-0.2.13-py_2
  flask-wtf          conda-forge/noarch::flask-wtf-0.14.3-py_0
  flower             conda-forge/linux-64::flower-0.9.5-py38h32f6830_0
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-2.001-hab24e00_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.030-hab24e00_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h1056068_1002
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  fribidi            conda-forge/linux-64::fribidi-1.0.10-h516909a_0
  funcsigs           conda-forge/noarch::funcsigs-1.0.2-py_3
  furl               conda-forge/noarch::furl-2.1.0-py_0
  future             conda-forge/linux-64::future-0.18.2-py38h32f6830_1
  gdk-pixbuf         conda-forge/linux-64::gdk-pixbuf-2.38.2-h3f25603_4
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  giflib             conda-forge/linux-64::giflib-5.2.1-h516909a_2
  glib               conda-forge/linux-64::glib-2.66.1-h680cd38_0
  gobject-introspec~ conda-forge/linux-64::gobject-introspection-1.66.1-py38h03d966d_0
  graphite2          conda-forge/linux-64::graphite2-1.3.13-he1b5a44_1001
  graphviz           conda-forge/linux-64::graphviz-2.42.3-h6939c30_1
  gtk2               conda-forge/linux-64::gtk2-2.24.32-h194ddfc_3
  gts                conda-forge/linux-64::gts-0.7.6-h08bb679_0
  gunicorn           conda-forge/linux-64::gunicorn-20.0.4-py38h32f6830_1
  harfbuzz           conda-forge/linux-64::harfbuzz-2.7.2-hee91db6_0
  humanize           conda-forge/noarch::humanize-3.0.1-py_0
  icu                conda-forge/linux-64::icu-67.1-he1b5a44_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-2.0.0-py38h32f6830_0
  importlib_metadata conda-forge/noarch::importlib_metadata-2.0.0-0
  infinity           conda-forge/noarch::infinity-1.4-py_0
  intervals          conda-forge/noarch::intervals-0.8.1-py_0
  iso8601            conda-forge/noarch::iso8601-0.1.13-pyh9f0ad1d_0
  itsdangerous       conda-forge/noarch::itsdangerous-1.1.0-py_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jpeg               conda-forge/linux-64::jpeg-9d-h516909a_0
  json-merge-patch   conda-forge/noarch::json-merge-patch-0.2-py_0
  jsonschema         conda-forge/linux-64::jsonschema-3.1.1-py38_0
  kombu              conda-forge/linux-64::kombu-4.6.11-py38h32f6830_0
  lazy-object-proxy  conda-forge/linux-64::lazy-object-proxy-1.3.1-py38h516909a_1001
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35-h769bd43_9
  libblas            conda-forge/linux-64::libblas-3.8.0-17_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-17_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hae1eefd_17
  libgfortran4       conda-forge/linux-64::libgfortran4-7.5.0-hae1eefd_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  liblapack          conda-forge/linux-64::liblapack-3.8.0-17_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.10-pthreads_hb3c22a3_4
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h2ae2ef3_17
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc7e4089_6
  libtool            conda-forge/linux-64::libtool-2.4.6-h516909a_1005
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libwebp            conda-forge/linux-64::libwebp-1.1.0-h56121f0_4
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h516909a_3
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.10-h68273f3_2
  lockfile           conda-forge/noarch::lockfile-0.12.2-py_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_3
  mako               conda-forge/noarch::mako-1.1.3-pyh9f0ad1d_0
  markdown           conda-forge/noarch::markdown-2.6.11-py_0
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h1e0a361_1
  marshmallow        conda-forge/noarch::marshmallow-2.19.5-py_0
  marshmallow-enum   conda-forge/linux-64::marshmallow-enum-1.5.1-py38h32f6830_1
  marshmallow-sqlal~ conda-forge/noarch::marshmallow-sqlalchemy-0.23.1-py_0
  natsort            conda-forge/noarch::natsort-7.0.1-py_0
  ncurses            conda-forge/linux-64::ncurses-6.2-he1b5a44_1
  numpy              conda-forge/linux-64::numpy-1.19.1-py38hbc27379_2
  openssl            conda-forge/linux-64::openssl-1.1.1h-h516909a_0
  orderedmultidict   conda-forge/noarch::orderedmultidict-1.0.1-py_0
  pandas             conda-forge/linux-64::pandas-1.1.3-py38h950e882_0
  pango              conda-forge/linux-64::pango-1.42.4-h7062337_4
  passlib            conda-forge/noarch::passlib-1.7.3-pyh9f0ad1d_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pendulum           conda-forge/linux-64::pendulum-1.4.4-py38_1
  phonenumbers       conda-forge/noarch::phonenumbers-8.10.14-py_0
  pip                conda-forge/noarch::pip-20.2.3-py_0
  pixman             conda-forge/linux-64::pixman-0.38.0-h516909a_1003
  prison             conda-forge/noarch::prison-0.1.3-pyh9f0ad1d_0
  prometheus_client  conda-forge/noarch::prometheus_client-0.8.0-pyh9f0ad1d_0
  psutil             conda-forge/linux-64::psutil-5.7.2-py38h1e0a361_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pygments           conda-forge/noarch::pygments-2.7.1-py_0
  pyjwt              conda-forge/noarch::pyjwt-1.7.1-py_0
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyrsistent         conda-forge/linux-64::pyrsistent-0.17.3-py38h1e0a361_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py38h32f6830_1
  python             conda-forge/linux-64::python-3.8.6-h852b56e_0_cpython
  python-daemon      conda-forge/linux-64::python-daemon-2.2.4-py38_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python-editor      conda-forge/noarch::python-editor-1.0.4-py_0
  python-graphviz    conda-forge/noarch::python-graphviz-0.14.2-pyh9f0ad1d_0
  python-nvd3        conda-forge/noarch::python-nvd3-0.15.0-pyh9f0ad1d_2
  python-slugify     conda-forge/noarch::python-slugify-4.0.1-pyh9f0ad1d_0
  python3-openid     conda-forge/linux-64::python3-openid-3.1.0-py38h32f6830_1002
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  pytzdata           conda-forge/noarch::pytzdata-2020.1-pyh9f0ad1d_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py38h1e0a361_0
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  requests           conda-forge/noarch::requests-2.24.0-pyh9f0ad1d_0
  setproctitle       conda-forge/linux-64::setproctitle-1.1.10-py38h1e0a361_1002
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h32f6830_1
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlalchemy         conda-forge/linux-64::sqlalchemy-1.3.19-py38h1e0a361_0
  sqlalchemy-jsonfi~ conda-forge/noarch::sqlalchemy-jsonfield-0.9.0-py_2
  sqlalchemy-utils   conda-forge/noarch::sqlalchemy-utils-0.36.6-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.33.0-h4cf870e_1
  tabulate           conda-forge/noarch::tabulate-0.8.7-pyh9f0ad1d_0
  tenacity           conda-forge/linux-64::tenacity-4.12.0-py38_0
  text-unidecode     conda-forge/noarch::text-unidecode-1.3-py_0
  thrift             conda-forge/linux-64::thrift-0.13.0-py38h950e882_1
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_1
  tornado            conda-forge/linux-64::tornado-5.1.1-py38h1e0a361_1
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.2-py_0
  tzlocal            conda-forge/noarch::tzlocal-1.5.1-py_0
  unicodecsv         conda-forge/noarch::unicodecsv-0.14.1-py_1
  unidecode          conda-forge/noarch::unidecode-1.1.1-py_0
  urllib3            conda-forge/noarch::urllib3-1.25.10-py_0
  vine               conda-forge/noarch::vine-1.3.0-py_0
  werkzeug           conda-forge/noarch::werkzeug-0.16.1-py_0
  wheel              conda-forge/noarch::wheel-0.35.1-pyh9f0ad1d_0
  wtforms            conda-forge/noarch::wtforms-2.3.2-pyh9f0ad1d_0
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.12-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxpm        conda-forge/linux-64::xorg-libxpm-3.5.13-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-libxt         conda-forge/linux-64::xorg-libxt-1.1.5-h516909a_1003
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  zipp               conda-forge/noarch::zipp-3.3.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1009
  zope.deprecation   conda-forge/noarch::zope.deprecation-4.4.0-py_0
  zstd               conda-forge/linux-64::zstd-1.4.5-h6597ccf_2



Downloading and Extracting Packages
airflow-1.10.12      | 4.1 MB    | ##################################### | 100% 
python-3.8.6         | 22.1 MB   | ##################################### | 100% 
airflow-with-celery- | 13 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

</details>

```
$ conda activate test
$ python -c "import celery"
```
(No output, as expected)

```
$ conda info
```
<details>

```
     active environment : test
    active env location : /home/xylar/miniconda3/envs/test
            shell level : 2
       user config file : /home/xylar/.condarc
 populated config files : /home/xylar/.condarc
          conda version : 4.8.5
    conda-build version : 3.20.2
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/xylar/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xylar/miniconda3/pkgs
                          /home/xylar/.conda/pkgs
       envs directories : /home/xylar/miniconda3/envs
                          /home/xylar/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.6 Linux/4.15.0-1097-oem ubuntu/18.04.5 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</details>

```
$ conda list
```
<details>

```
# packages in environment at /home/xylar/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
airflow                   1.10.12          py38h32f6830_2    conda-forge
airflow-with-celery       1.10.12                       2    conda-forge
alembic                   1.4.3              pyh9f0ad1d_0    conda-forge
amqp                      2.6.1              pyh9f0ad1d_0    conda-forge
anyjson                   0.3.3                 py38_1001    conda-forge
apispec                   1.3.3                      py_0    conda-forge
argcomplete               1.10.3                     py_0    conda-forge
argon2-cffi               20.1.0           py38h1e0a361_1    conda-forge
arrow                     0.17.0           py38h32f6830_0    conda-forge
atk                       2.36.0                        2    conda-forge
atk-1.0                   2.36.0               h516909a_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
bcrypt                    3.2.0            py38h1e0a361_0    conda-forge
billiard                  3.6.3.0          py38h516909a_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
cattrs                    1.0.0                      py_0    conda-forge
celery                    4.4.0rc1                   py_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.3           py38h5bae8af_0    conda-forge
chardet                   3.0.4           py38h32f6830_1007    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
colorlog                  4.0.2                 py38_1000    conda-forge
colour                    0.1.5                      py_0    conda-forge
configparser              3.5.0                   py_1000    conda-forge
croniter                  0.3.34             pyh9f0ad1d_0    conda-forge
cryptography              3.1.1            py38h766eaa4_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
dill                      0.3.2              pyh9f0ad1d_0    conda-forge
dnspython                 2.0.0                      py_0    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
email-validator           1.1.1              pyh9f0ad1d_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
flask-admin               1.5.4                      py_0    conda-forge
flask-appbuilder          2.2.4                      py_0    conda-forge
flask-babel               1.0.0                      py_0    conda-forge
flask-caching             1.3.3                      py_0    conda-forge
flask-jwt-extended        3.24.1             pyh9f0ad1d_0    conda-forge
flask-login               0.4.1                      py_0    conda-forge
flask-openid              1.2.5                 py38_1003    conda-forge
flask-sqlalchemy          2.4.4              pyh9f0ad1d_0    conda-forge
flask-swagger             0.2.13                     py_2    conda-forge
flask-wtf                 0.14.3                     py_0    conda-forge
flower                    0.9.5            py38h32f6830_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
furl                      2.1.0                      py_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gdk-pixbuf                2.38.2               h3f25603_4    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.66.1               h680cd38_0    conda-forge
gobject-introspection     1.66.1           py38h03d966d_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
graphviz                  2.42.3               h6939c30_1    conda-forge
gtk2                      2.24.32              h194ddfc_3    conda-forge
gts                       0.7.6                h08bb679_0    conda-forge
gunicorn                  20.0.4           py38h32f6830_1    conda-forge
harfbuzz                  2.7.2                hee91db6_0    conda-forge
humanize                  3.0.1                      py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        2.0.0            py38h32f6830_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
infinity                  1.4                        py_0    conda-forge
intervals                 0.8.1                      py_0    conda-forge
iso8601                   0.1.13             pyh9f0ad1d_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-merge-patch          0.2                        py_0    conda-forge
jsonschema                3.1.1                    py38_0    conda-forge
kombu                     4.6.11           py38h32f6830_0    conda-forge
lazy-object-proxy         1.3.1           py38h516909a_1001    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libtool                   2.4.6             h516909a_1005    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.1.0                h56121f0_4    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
mako                      1.1.3              pyh9f0ad1d_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
marshmallow               2.19.5                     py_0    conda-forge
marshmallow-enum          1.5.1            py38h32f6830_1    conda-forge
marshmallow-sqlalchemy    0.23.1                     py_0    conda-forge
natsort                   7.0.1                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py38hbc27379_2    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
pandas                    1.1.3            py38h950e882_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
passlib                   1.7.3              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pendulum                  1.4.4                    py38_1    conda-forge
phonenumbers              8.10.14                    py_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prison                    0.1.3              pyh9f0ad1d_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
psutil                    5.7.2            py38h1e0a361_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyrsistent                0.17.3           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.6           h852b56e_0_cpython    conda-forge
python-daemon             2.2.4                    py38_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-graphviz           0.14.2             pyh9f0ad1d_0    conda-forge
python-nvd3               0.15.0             pyh9f0ad1d_2    conda-forge
python-slugify            4.0.1              pyh9f0ad1d_0    conda-forge
python3-openid            3.1.0           py38h32f6830_1002    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pytzdata                  2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
setproctitle              1.1.10          py38h1e0a361_1002    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.19           py38h1e0a361_0    conda-forge
sqlalchemy-jsonfield      0.9.0                      py_2    conda-forge
sqlalchemy-utils          0.36.6             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
tenacity                  4.12.0                   py38_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
thrift                    0.13.0           py38h950e882_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   5.1.1            py38h1e0a361_1    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
tzlocal                   1.5.1                      py_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unidecode                 1.1.1                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vine                      1.3.0                      py_0    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wtforms                   2.3.2              pyh9f0ad1d_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.3.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zope.deprecation          4.4.0                      py_0    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

</details>

**Comment by xylar** [comment]
It, Is odd that mine is picking up `4.4.0rc1`, which probably shouldn't be available.  It should have been on a `dev` channel.  The contstraint from upstream is `celery~=4.3`, so it might be worth explicitly pinning 4.3 in your install.

**Comment by zhangyi-hu** [comment]
It is the problem of the previous version:

I installed by:

`conda install -c conda-forge python=3.7 airflow-with-celery=1.10.11
`

1.10.12 doesn't have this problem. 

I didn't notice that you updated the version, and thought this problem still exists. 

```
conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
airflow                   1.10.11          py37hc8dfbb8_3    conda-forge
airflow-with-celery       1.10.11                       3    conda-forge
alembic                   1.4.3              pyh9f0ad1d_0    conda-forge
.... 
unidecode                 1.1.1                      py_0    conda-forge
urllib3                   1.25.8                   py37_0  
vine                      5.0.0              pyh9f0ad1d_0    conda-forge
werkzeug                  0.16.1                     py_0    conda-forge
wheel                     0.34.2                   py37_0  
wtforms                   2.3.2              pyh9f0ad1d_0    conda-forge

```

Problem:

```
celery --version 
Traceback (most recent call last):
  File "/opt/conda/bin/celery", line 6, in <module>
    from celery.__main__ import main
  File "/opt/conda/lib/python3.7/site-packages/celery/__init__.py", line 153, in <module>
    from . import local  # noqa
  File "/opt/conda/lib/python3.7/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/opt/conda/lib/python3.7/site-packages/celery/five.py", line 7, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'

```

You might want to provide another build for older versions in case the user needs specific versions of airflow.

**Comment by zhangyi-hu** [comment]
The problem is fixed in the latest 1.10.12 build.

**Comment by zhangyi-hu** [comment]
The problem is fixed in the latest 1.10.12 build.

**Comment by xylar** [comment]
> You might want to provide another build for older versions in case the user needs specific versions of airflow.

I could do that but it's a significant amount of work for a problem that is frankly not caused by this feedstock but rather by celery.  The fix would be to move `celery` 4.4.0rc1 to a `dev` label and make a build of `celery` 4.3.0 that constrains `vine<5.0.0`.  But, given that this is a pretty old version of `celery`, I woudl guess the maintainers will not be interested in doing that.

My suggestion to users of `airflow-with-celery` 1.10.11 would be to just add `vine >=1.3.0,<5.5.0` as part of your install command and you'll be set.

**Comment by zhangyi-hu** [comment]
Agree, I'm glad at least it is fixed on this end with 1.10.12.
